### PR TITLE
[Misc] Training app bring-up

### LINKED ISSUE #4: Project bring-up

### PR DESCRIPTION
**Pull request by SferaDev**
- **Issue:** Closes #4

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
@SferaDev following eslint output there's a problem with IFrame. It's identified as an error because it's an interface and starts by capital i. If there's any way to exclude this particular situation from eslint checks to avoid needing to bypass eslint for pushing to the repo, that would be great. 

```
/home/nacho/EyeSeeTea/code/dhis2-web/dev-repos/training-app/src/webapp/components/iframe/IFrame.tsx
  5:18  error  Interface name must not be prefixed with "I"  @typescript-eslint/interface-name-prefix

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky > pre-push hook failed (add --no-verify to bypass)
error: failed to push some refs to 'https://github.com/EyeSeeTea/training-app.git'
```

In any case, compilation is failing for me with the following message:
```
Failed to compile.

./src/index.tsx
Attempted import error: 'D2Api' is not exported from './types/d2-api'.
```

Could you please have a look to this error? Thanks!

**Comment by SferaDev** [comment]
> @SferaDev following eslint output there's a problem with IFrame. It's identified as an error because it's an interface and starts by capital i. If there's any way to exclude this particular situation from eslint checks to avoid needing to bypass eslint for pushing to the repo, that would be great. 
> 
> In any case, compilation is failing for me with the following message:
>
> Could you please have a look to this error? Thanks!

@ifoche I believe you forgot to "yarn install" the new dependencies after changing branch.

The eslint interface-name-prefix rule was deprecated on the official naming conventions and shouldn't be there anymore, at least with the updated dependencies of this PR.

And the D2Api default export was also a breaking change we did implement on the 1.0.0 release of d2-api, so I guess you still have 0.x release on your local node_modules.

I will check now that it compiles just fine on my machine to make sure however, but this PR was intended as the [updates for skeleton-app](https://github.com/EyeSeeTea/dhis2-app-skeleton/pull/24) to keep it up-to-date and does not bring any major functionality to training-app.

**Comment by SferaDev** [comment]
@ifoche Just tested locally and there are no linter or compilation errors/warnings.

I have just added a ``post-merge`` hook so that when it detects a change on the lockfile it automatically updates the dependencies so that this does not happen in the future. I will bring it on to the next weekly meeting to see if we standardize it in the rest of apps.

**Comment by ifoche** [comment]
completely right @SferaDev , thanks for the clarification!

**Review by ifoche — APPROVED** [review]
thanks @SferaDev

**Pull request merged**
