### PR TITLE
[Merge] Release 0.3.0

### PR DESCRIPTION
**Pull request by SferaDev**
New features:

- Add Event visualizer module (#98)
- Add Data visualizer module (#105)
- Add Pivot tables module (#106)
- Add Maps module (#107)
- Add Bulk Load module (#108)
- Make text in "What will this tutorial cover" page interactive as the icon (#102)
- Make it clearer when there are multiple pages per step (Step 1 of 3) (#63)
- Make it clearer that some “Optional” steps do not apply to all forms (#74)
- Update minimize behavior (#62)
- Add minimized icon to all dialogs (#101)
- Add intermediate exit dialog as close action (#60)
- Add a basic settings page (#14)
- Add live sync of translations (#92)
- Allow initializing POEditor from settings page (#93)
- Allow resetting progress from home page (#116)
- Allow non-admin users to visit settings page (#119)

Bugfixes:

- Add tooltip to exit button (#103)
- Reset scroll on step change (#86)
- Preload module images to browser cache (#40)
- Update behavior for progress advancement (#100)

Known issues:

- Browser back button does not properly work (#52)
- Modules are not hidden if user does not have access (#84)
- Training app disappears off the screen if moved and cannot be retrieved (#72)
- Modal looks misplaced on smaller screens (#23)
- Module name cannot be translated (#113)

### CODE REVIEW

**Comment by idelcano** [comment]
When I complete a module, I see the message "Well Done", if I click next, instead of going to the selection of modules, I see the index of the module (what did you learn in this tutorial?), If I press next again, the app moves to the module selection.

Is it a desired feature to show the list of steps after finishing the module?

**Comment by idelcano** [comment]
When I start the event-capture training I get an error 404 in dhis2
http://localhost:8080/api/apps/Training-App/index.html#/tutorial/event-capture/welcome

The old event-capture app no ​​longer exists in 2.34.
It should point to the new app:
http://localhost:8080/dhis-web-capture/index.html

**Comment by idelcano** [comment]
I can't select trainning app from capture app:
trainningapp

**Comment by SferaDev** [comment]
> When I complete a module, I see the message "Well Done", if I click next, instead of going to the selection of modules, I see the index of the module (what did you learn in this tutorial?), If I press next again, the app moves to the module selection.
> 
> Is it a desired feature to show the list of steps after finishing the module?

Desired feature

> When I start the event-capture training I get an error 404 in dhis2
> http://localhost:8080/api/apps/Training-App/index.html#/tutorial/event-capture/welcome
> 
> The old event-capture app no ​​longer exists in 2.34.
> It should point to the new app:
> http://localhost:8080/dhis-web-capture/index.html

Got it!

> I can't select trainning app from capture app:
> trainningapp

Issue on old header bar, search does include custom apps. I fixed this in ``dhis2/ui-widgets`` on January but seems the 2.34 version still didn't get the patch: https://github.com/dhis2/ui-widgets/pull/274

**Comment by idelcano** [comment]
Some texts have line breaks and some do not.
I think it is more readable with more line breaks in general.

screenshot-localhost_8080-2020 11 30-17_24_26

screenshot-localhost_8080-2020 11 30-17_24_06

**Comment by SferaDev** [comment]
> Some texts have line breaks and some do not.
> I think it is more readable with more line breaks in general.

Yes, but we didn't write the text, we have followed what they sent us. Will add as a note on the release email.

**Comment by idelcano** [comment]
data visualizer:

url has changed in 2.34
screenshot-localhost_8080-2020 11 30-17_52_18
new url:
http://localhost:8080/dhis-web-data-visualizer/index.html#/

**Comment by idelcano** [comment]
screenshot-localhost_8080-2020 11 30-18_20_48
First load never ends

It can be replicated by deleting the datastore, and installing the app.

**Comment by ifoche** [comment]
Not for now but maybe we can create the ticket to make access settings behave like other similar components. Show from outside the number of users/usergroups that have been granted with access (e.g. bulk load app):

Training app:
screenshots_1606766273_2057_30112020_521x133

Bulk Load app:
screenshots_1606766360_2059_30112020_337x114

**Comment by ifoche** [comment]
Maybe also for the future as it's not very important, but if there's no bulk action maybe we can just remove the checkboxes from the settings object table...right?
screenshots_1606766607_2103_30112020_360x153

**Comment by ifoche** [comment]
Once completed...
screenshots_1606766905_2108_30112020_140x135

...I open maps tutorial, and then go to step 3. I click on the home icon and... maps is still in 100% progress. Shouldn't it be a lower percentage?

**Comment by ifoche** [comment]
I change  the welcome message for Maps app, 
screenshots_1606767064_2111_30112020_1101x221


but I cannot get it into the app, even reloading
screenshots_1606767125_2112_30112020_705x220

**Comment by ifoche** [comment]
> When I start the event-capture training I get an error 404 in dhis2
> http://localhost:8080/api/apps/Training-App/index.html#/tutorial/event-capture/welcome
> 
> The old event-capture app no ​​longer exists in 2.34.
> It should point to the new app:
> http://localhost:8080/dhis-web-capture/index.html

I'm not sure about this. I think the training shouldn't display if you don't have the app. Taking the user to a different app will confuse him/her, as what the training display is completely different from what the user see. From what I can see, the module shows (at least in the animated gifs) the new capture app. Why should it be called then event capture? I think that's not clear. IMHO I wouldn't show a training on capture app in 2.30 where capture doesn't exist

**Review by ifoche — CHANGES_REQUESTED** [review]
Not a lot to add on what Ina already discover. I think my only concern would be my last 2 comments but for the rest it's wonderful

**Comment by SferaDev** [comment]
> screenshot-localhost_8080-2020 11 30-18_20_48
> First load never ends
> 
> It can be replicated by deleting the datastore, and installing the app.

Fixed

> Maybe also for the future as it's not very important, but if there's no bulk action maybe we can just remove the checkboxes from the settings object table...right?
> screenshots_1606766607_2103_30112020_360x153

Not yet, we have a bug in d2-ui-components: https://github.com/EyeSeeTea/d2-ui-components/issues/184

**Pull request merged**
